In [1]:
import pandas as pd
import seaborn as sns

import vindta_reCAlk as vr

In [2]:
dbs_filename = './test_data/Gough2013.dbs'
datfiles_dir = './test_data/'
xls_filename = './test_data/output.xlsx'

In [4]:
df = vr.dbs_to_excel(
    dbs_filename,
    datfiles_dir,
    xls_filename,
    acidconcL=0.1,
    aciddens=1.02266027,
    pipVol=97.846,
    pKchoice=13,
    po4=0.5,
    sio4=2.12,
    factorCT=1.0
)

,bottle,station,cast,niskin,depth,temp,salt,counts,runtime,dic,...,analysis_date,runtype,datfilename,xls_filename,pKchoice,po4,sio4,pK1,pK_constant,verbose
0,CRM0001340629A,1.0,1.0,1.0,1.0,25.0,33.651,199813.0,8.0,2015.11,...,2014-04-08 11:15:00,bottle,./test_data/1-1 1 (1)CRM0001340629A.dat,./test_data/output.xlsx,13,0.5,2.12,5.842115,"Millero, 2010",False
1,CRM0001340629B,1.0,1.0,1.0,1.0,25.0,33.651,199589.0,9.0,2011.32,...,2014-04-08 11:46:00,bottle,./test_data/1-1 1 (1)CRM0001340629B.dat,./test_data/output.xlsx,13,0.5,2.12,5.836919,"Millero, 2010",False
2,CRM0001340629C,1.0,1.0,1.0,1.0,25.0,33.651,198536.0,9.0,2000.63,...,2014-04-08 12:10:00,bottle,./test_data/1-1 1 (1)CRM0001340629C.dat,./test_data/output.xlsx,13,0.5,2.12,5.840521,"Millero, 2010",False
3,TEST20140409A,1.0,1.0,1.0,1.0,4.0,35.000,204367.0,9.0,2056.74,...,2014-04-09 10:37:00,bottle,./test_data/1-1 1 (1)TEST20140409A.dat,./test_data/output.xlsx,13,0.5,2.12,5.859193,"Millero, 2010",False
4,TEST20140409B,1.0,1.0,1.0,1.0,4.0,35.000,206800.0,9.0,2081.39,...,2014-04-09 11:03:00,bottle,./test_data/1-1 1 (1)TEST20140409B.dat,./test_data/output.xlsx,13,0.5,2.12,5.837531,"Millero, 2010",False
5,CRM0001341225A,1.0,1.0,1.0,1.0,25.0,33.651,201162.0,8.0,2027.81,...,2014-04-09 11:43:00,bottle,./test_data/1-1 1 (1)CRM0001341225A.dat,./test_data/output.xlsx,13,0.5,2.12,5.844541,"Millero, 2010",False
6,CRM0001341225B,1.0,1.0,1.0,1.0,25.0,33.651,198429.0,8.0,2000.09,...,2014-04-09 12:18:00,bottle,./test_data/1-1 1 (1)CRM0001341225B.dat,./test_data/output.xlsx,13,0.5,2.12,5.841897,"Millero, 2010",False
7,GHG20130905196A,1.0,1.0,12.0,5.0,25.0,35.000,202892.0,8.0,2044.74,...,2014-04-09 12:48:00,bottle,./test_data/1-1 12 (5)GHG20130905196A.dat,./test_data/output.xlsx,13,0.5,2.12,5.836638,"Millero, 2010",False
8,GHG20130905146,1.0,1.0,12.0,5.0,25.0,35.000,203901.0,8.0,2054.97,...,2014-04-09 13:10:00,bottle,./test_data/1-1 12 (5)GHG20130905146.dat,./test_data/output.xlsx,13,0.5,2.12,5.833128,"Millero, 2010",False
9,GHG20130905189,1.0,1.0,12.0,5.0,25.0,35.000,203393.0,8.0,2049.82,...,2014-04-09 13:41:00,bottle,./test_data/1-1 12 (5)GHG20130905189.dat,./test_data/output.xlsx,13,0.5,2.12,5.831925,"Millero, 2010",False
10,GHG20130905107,1.0,1.0,12.0,5.0,25.0,35.000,203050.0,8.0,2046.34,...,2014-04-09 14:03:00,bottle,./test_data/1-1 12 (5)GHG20130905107.dat,./test_data/output.xlsx,13,0.5,2.12,5.834140,"Millero, 2010",False
11,GHG20130905182,1.0,1.0,12.0,5.0,25.0,35.000,202947.0,8.0,2045.30,...,2014-04-09 14:27:00,bottle,./test_data/1-1 12 (5)GHG20130905182.dat,./test_data/output.xlsx,13,0.5,2.12,5.833865,"Millero, 2010",False
12,GHG20130905110,1.0,1.0,12.0,5.0,25.0,35.000,203300.0,8.0,2048.87,...,2014-04-09 14:48:00,bottle,./test_data/1-1 12 (5)GHG20130905110.dat,./test_data/output.xlsx,13,0.5,2.12,5.832008,"Millero, 2010",False
13,GHG20130905159,1.0,1.0,12.0,5.0,25.0,35.000,201067.0,8.0,2026.24,...,2014-04-09 15:10:00,bottle,./test_data/1-1 12 (5)GHG20130905159.dat,./test_data/output.xlsx,13,0.5,2.12,5.833506,"Millero, 2010",False
14,CRM0001341012A,1.0,1.0,1.0,1.0,25.0,33.651,197952.0,8.0,1996.22,...,2014-04-09 15:36:00,bottle,./test_data/1-1 1 (1)CRM0001341012A.dat,./test_data/output.xlsx,13,0.5,2.12,5.846492,"Millero, 2010",False
15,CRM0001341012B,1.0,1.0,1.0,1.0,25.0,33.651,197062.0,8.0,1987.19,...,2014-04-09 15:59:00,bottle,./test_data/1-1 1 (1)CRM0001341012B.dat,./test_data/output.xlsx,13,0.5,2.12,5.850183,"Millero, 2010",False
16,TEST20140410A,1.0,1.0,1.0,1.0,4.0,35.000,204152.0,8.0,2056.06,...,2014-04-10 09:59:00,bottle,./test_data/1-1 1 (1)TEST20140410A.dat,./test_data/output.xlsx,13,0.5,2.12,5.837187,"Millero, 2010",False
17,TEST20140410B,1.0,1.0,1.0,1.0,4.0,35.000,204605.0,10.0,2057.61,...,2014-04-10 10:22:00,bottle,./test_data/1-1 1 (1)TEST20140410B.dat,./test_data/output.xlsx,13,0.5,2.12,5.836558,"Millero, 2010",False
18,CRM0001341021A,1.0,1.0,1.0,1.0,25.0,33.651,199153.0,9.0,2005.90,...,2014-04-10 10:47:00,bottle,./test_data/1-1 1 (1)CRM0001341021A.dat,./test_data/output.xlsx,13,0.5,2.12,5.835956,"Millero, 2010",False
19,CRM0001341021B,1.0,1.0,1.0,1.0,25.0,33.651,198170.0,8.0,1997.45,...,2014-04-10 11:09:00,bottle,./test_data/1-1 1 (1)CRM0001341021B.dat,./test_data/output.xlsx,13,0.5,2.12,5.832189,"Millero, 2010",False
20,GHG20130906109,1.0,1.0,1.0,5.0,25.0,35.000,203335.0,8.0,2047.79,...,2014-04-10 11:50:00,bottle,./test_data/1-1 1 (5)GHG20130906109.dat,./test_data/output.xlsx,13,0.5,2.12,5.833464,"Millero, 2010",False
21,GHG20130906156,1.0,1.0,1.0,5.0,25.0,35.000,203826.0,8.0,2052.76,...,2014-04-10 12:14:00,bottle,./test_data/1-1 1 (5)GHG20130906156.dat,./test_data/output.xlsx,13,0.5,2.12,5.825619,"Millero, 2010",False
22,GHG20130906118,1.0,1.0,1.0,5.0,25.0,35.000,205624.0,8.0,2070.98,...,2014-04-10 12:42:00,bottle,./test_data/1-1 1 (5)GHG20130906118.dat,./test_data/output.xlsx,13,0.5,2.12,5.831303,"Millero, 2010",False
23,GHG20130907206,1.0,1.0,1.0,5.0,25.0,35.000,204610.0,9.0,2059.19,...,2014-04-10 13:04:00,bottle,./test_data/1-1 1 (5)GHG20130907206.dat,./test_data/output.xlsx,13,0.5,2.12,5.833218,"Millero, 2010",False
24,GHG20130907106,1.0,1.0,1.0,5.0,25.0,35.000,203852.0,8.0,2053.03,...,2014-04-10 13:35:00,bottle,./test_data/1-1 1 (5)GHG20130907106.dat,./test_data/output.xlsx,13,0.5,2.12,5.832148,"Millero, 2010",False
25,GHG20130907123,1.0,1.0,1.0,5.0,25.0,35.000,202823.0,8.0,2042.60,...,2014-04-10 14:00:00,bottle,./test_data/1-1 1 (5)GHG20130907123.dat,./test_data/output.xlsx,13,0.5,2.12,5.835381,"Millero, 2010",False
26,GHG20130907115,1.0,1.0,1.0,5.0,25.0,35.000,203167.0,8.0,2046.09,...,2014-04-10 14:25:00,bottle,./test_data/1-1 1 (5)GHG20130907115.dat,./test_data/output.xlsx,13,0.5,2.12,5.838229,"Millero, 2010",False
27,GHG20130907114,1.0,1.0,1.0,5.0,25.0,35.000,204217.0,8.0,2056.72,...,2014-04-10 14:48:00,bottle,./test_data/1-1 1 (5)GHG20130907114.dat,./test_data/output.xlsx,13,0.5,2.12,5.837365,"Millero, 2010",False
28,GHG20130907181,1.0,1.0,1.0,5.0,25.0,35.000,204897.0,8.0,2063.61,...,2014-04-10 15:11:00,bottle,./test_data/1-1 1 (5)GHG20130907181.dat,./test_data/output.xlsx,13,0.5,2.12,5.837901,"Millero, 2010",False
29,GHG20130907185,1.0,1.0,1.0,5.0,25.0,35.000,204441.0,8.0,2058.99,...,2014-04-10 15:34:00,bottle,./test_data/1-1 1 (5)GHG20130907185.dat,./test_data/output.xlsx,13,0.5,2.12,5.830070,"Millero, 2010",False
30,CRM0001340784A,1.0,1.0,1.0,51.0,25.0,33.651,198667.0,8.0,2002.49,...,2014-04-10 15:57:00,bottle,./test_data/1-1 1 (51)CRM0001340784A.dat,./test_data/output.xlsx,13,0.5,2.12,5.846806,"Millero, 2010",False
31,CRM0001340784B,1.0,1.0,1.0,51.0,25.0,33.651,197942.0,8.0,1995.14,...,2014-04-10 16:19:00,bottle,./test_data/1-1 1 (51)CRM0001340784B.dat,./test_data/output.xlsx,13,0.5,2.12,5.839613,"Millero, 2010",False
32,TEST20140411AA,1.0,1.0,1.0,1.0,25.0,35.000,205895.0,8.0,2074.48,...,2014-04-11 10:30:00,bottle,./test_data/1-1 1 (1)TEST20140411AA.dat,./test_data/output.xlsx,13,0.5,2.12,5.839635,"Millero, 2010",False
33,TEST20140411B,1.0,1.0,1.0,1.0,25.0,35.000,206072.0,10.0,2073.23,...,2014-04-11 10:52:00,bottle,./test_data/1-1 1 (1)TEST20140411B.dat,./test_data/output.xlsx,13,0.5,2.12,5.839543,"Millero, 2010",False
34,CRM0001340904A,1.0,1.0,1.0,1.0,25.0,33.651,197596.0,9.0,1990.83,...,2014-04-11 11:16:00,bottle,./test_data/1-1 1 (1)CRM0001340904A.dat,./test_data/output.xlsx,13,0.5,2.12,5.841376,"Millero, 2010",False
35,CRM0001340904B,1.0,1.0,1.0,1.0,25.0,33.651,197629.0,9.0,1991.17,...,2014-04-11 11:39:00,bottle,./test_data/1-1 1 (1)CRM0001340904B.dat,./test_data/output.xlsx,13,0.5,2.12,5.843127,"Millero, 2010",False
36,CRM0001340904C,1.0,1.0,1.0,1.0,25.0,33.651,197473.0,8.0,1991.11,...,2014-04-11 12:11:00,bottle,./test_data/1-1 1 (1)CRM0001340904C.dat,./test_data/output.xlsx,13,0.5,2.12,5.842409,"Millero, 2010",False
37,GHG20130908157,1.0,1.0,1.0,1.0,25.0,35.000,202967.0,9.0,2043.29,...,2014-04-11 12:40:00,bottle,./test_data/1-1 1 (1)GHG20130908157.dat,./test_data/output.xlsx,13,0.5,2.12,5.836110,"Millero, 2010",False
38,GHG20130908104,1.0,1.0,1.0,1.0,25.0,35.000,203179.0,8.0,2046.96,...,2014-04-11 13:09:00,bottle,./test_data/1-1 1 (1)GHG20130908104.dat,./test_data/output.xlsx,13,0.5,2.12,5.836567,"Millero, 2010",False
39,GHG20130908120,1.0,1.0,1.0,1.0,25.0,35.000,203511.0,8.0,2050.32,...,2014-04-11 13:34:00,bottle,./test_data/1-1 1 (1)GHG20130908120.dat,./test_data/output.xlsx,13,0.5,2.12,5.836145,"Millero, 2010",False
40,GHG20130908195,1.0,1.0,1.0,1.0,25.0,35.000,204176.0,8.0,2057.06,...,2014-04-11 14:05:00,bottle,./test_data/1-1 1 (1)GHG20130908195.dat,./test_data/output.xlsx,13,0.5,2.12,5.838650,"Millero, 2010",False
41,GHG20130909192,1.0,1.0,1.0,1.0,25.0,35.000,204177.0,8.0,2057.07,...,2014-04-11 14:34:00,bottle,./test_data/1-1 1 (1)GHG20130909192.dat,./test_data/output.xlsx,13,0.5,2.12,5.838683,"Millero, 2010",False
42,GHG20130908117,1.0,1.0,1.0,1.0,25.0,35.000,204337.0,10.0,2055.65,...,2014-04-11 14:58:00,bottle,./test_data/1-1 1 (1)GHG20130908117.dat,./test_data/output.xlsx,13,0.5,2.12,5.834859,"Millero, 2010",False
43,GHG20130908200,1.0,1.0,1.0,1.0,25.0,35.000,204111.0,8.0,2056.40,...,2014-04-11 15:25:00,bottle,./test_data/1-1 1 (1)GHG20130908200.dat,./test_data/output.xlsx,13,0.5,2.12,5.837637,"Millero, 2010",False
44,GHG20130908119,1.0,1.0,1.0,1.0,25.0,35.000,204414.0,8.0,2059.47,...,2014-04-11 15:48:00,bottle,./test_data/1-1 1 (1)GHG20130908119.dat,./test_data/output.xlsx,13,0.5,2.12,5.837601,"Millero, 2010",False
45,CRM0001340843A,1.0,1.0,1.0,1.0,25.0,33.651,198127.0,8.0,1997.74,...,2014-04-11 16:11:00,bottle,./test_data/1-1 1 (1)CRM0001340843A.dat,./test_data/output.xlsx,13,0.5,2.12,5.843827,"Millero, 2010",False
46,CRM0001340843B,1.0,1.0,1.0,1.0,25.0,33.651,197641.0,8.0,1992.81,...,2014-04-11 16:34:00,bottle,./test_data/1-1 1 (1)CRM0001340843B.dat,./test_data/output.xlsx,13,0.5,2.12,5.838418,"Millero, 2010",False
47,CRM0001340843C,1.0,1.0,1.0,1.0,25.0,33.651,197326.0,8.0,1989.61,...,2014-04-11 16:57:00,bottle,./test_data/1-1 1 (1)CRM0001340843C.dat,./test_data/output.xlsx,13,0.5,2.12,5.843844,"Millero, 2010",False